// Every number here was read off disk on 2026-09-23. Nothing is invented.
const DATA = {
  generated: "2026-09-23",
  apps: [
    { id:"app_1", name:"DesignMyRoom", tag:"the decor app",
      problem:"Restyle a room photo without inventing architecture",
      stage:7, commits:119, pages:8, decisions:62, started:"2026-09-06", detail:true },
    { id:"app_2", name:"Focus", tag:"social blocker",
      problem:"Cut social media use, regain focus (iPhone)",
      stage:1, commits:0, pages:1, decisions:0, started:"2026-09-18", detail:false },
    { id:"app_3", name:"What to Cook", tag:"three dinners",
      problem:"Three dinners from what is in the fridge, under today's calories",
      stage:3, commits:0, pages:1, decisions:8, started:"2026-09-19", detail:false },
    { id:"app_4", name:"Earn Your Scroll", tag:"earn minutes",
      problem:"Real-life actions buy TikTok / Instagram minutes (iPhone)",
      stage:6, commits:0, pages:3, decisions:34, started:"2026-09-19", detail:false }
  ],
  stages: ["Research","Positioning","Spec","Design","Contract freeze","Build v1","Features","Ship"],
  // board cells: doc counts per app per stage
  board: {
    app_1:[{n:2},{n:1},{n:4},null,{n:1},{n:3},{n:6},null],
    app_2:[{n:2},null,null,null,null,null,null,null],
    app_3:[{n:2},{n:1},null,null,null,null,null,null],
    app_4:[{n:2},{n:1},{n:3},{n:1},{n:1},{n:2},null,null]
  },
  // app_1 detail — stages, gates ticked from what is on disk, documents, side work
  app_1:{
    stages:[
      { n:1, name:"Research", state:"done", dates:"Sep 6",
        gates:[["research file written",true],["complaints verbatim with links",true],["strongest option named",true]],
        docs:[{t:"home-decorating.md",k:"md",id:"research"},{t:"decorai-options-teardown.md",k:"md",id:"teardown"}] },
      { n:2, name:"Positioning", state:"done", dates:"Sep 8",
        gates:[["positioning.md exists",true],["Anchored-to block present",true]],
        docs:[{t:"positioning.md",k:"md",id:"positioning"}] },
      { n:3, name:"Spec", state:"done", dates:"Sep 6 → 12",
        gates:[["review rounds held",true,"10 rounds"],["PRD exported from the page",true,"19 sections"],["clickable prototype built",false,"this app predates the rule"]],
        docs:[{t:"spec/",k:"hw",id:"spec"},{t:"PRD.md",k:"md",id:"prd"},{t:"spike/",k:"code",id:"spike"}],
        side:[{t:"ui_design_v2",id:"ui_design_v2"},{t:"prompt_review",id:"prompt_review"},{t:"options_review",id:"options_review"}] },
      { n:"3\u00bd", name:"Design direction", state:"skip", dates:"\u2014",
        gates:[["design/BRIEF.md written",false,"this app predates the stage"],["Claude Design handoff received",false]],
        docs:[] },
      { n:4, name:"Contract freeze", state:"done", dates:"Sep 9",
        gates:[["openapi.json committed",true,"12 routes"],["CI contract check",true,"backend.yml"],["both worker briefs point at it",true]],
        docs:[{t:"contract/openapi.json",k:"code",id:"contract"}] },
      { n:5, name:"Build v1", state:"done", dates:"Sep 9", v1:true,
        gates:[["PRD §18 build order complete",true,"40 commits in one day"],["both branches merged to main",true,"backend · ios"],["client runs end to end",true],["baseline items in (PRD §17)",true]],
        docs:[{t:"HANDOFF.md",k:"md",id:"handoff"},{t:"ORCH-QUESTIONS.md",k:"md",id:"orch"}] },
      { n:6, name:"Features", state:"now", dates:"Sep 10 → today", features:true, repeats:true,
        gates:[["features merged and verified",true,"6 so far"],["contract changes went through ORCH-QUESTIONS",true,"2 of 6 needed it"],["contract questions answered",false,"10 of 12"]],
        docs:[{t:"app_snapshot",k:"hw",id:"app_snapshot"}],
        side:[{t:"search_research",id:"search_research"},{t:"shopping_research",id:"shopping_research"},{t:"shopping_proto",id:"shopping_proto"}] },
      { n:7, name:"Ship", state:"todo", dates:"—",
        gates:[["deployed to a real host",false],["showcase site",false]], docs:[] }
    ],
    v1:{ date:"Sep 9", commits:40,
      backend:"migrations · storage · three-state health · auth + Sign in with Apple · rooms & photos · inventory · renders + worker · rate limiting · metrics · structured logging · error tracking · §17 failure tests",
      ios:"core package · APIClient · render state machine · HEIC→JPEG · session restore · all 7 screens" },
    features:[
      { id:"F1", t:"Visual redesign v2", sub:"All 7 screens restyled", when:"Sep 10", docs:[{t:"ui_design_v2",id:"ui_design_v2"}] },
      { id:"F2", t:"Style library 6 → 18", sub:"Prompt rewrite and the REMOVE fix, proven by a render-level acceptance test", when:"Sep 10", docs:[{t:"prompt_review",id:"prompt_review"}] },
      { id:"F3", t:"Home / room-history screen", sub:"No more auto-start into a fresh room", when:"Sep 10", docs:[] },
      { id:"F4", t:"The options round", sub:"Room type, walls, furniture, decor, plants, palette — 9 backend parts, 7 iOS commits", when:"Sep 11", docs:[{t:"options_review",id:"options_review"}] },
      { id:"F5", t:"Shop your restyle", sub:"Research → options A/B/C → prototype → build, both halves", when:"Sep 11–12", docs:[{t:"search_research",id:"search_research"},{t:"shopping_research",id:"shopping_research"},{t:"shopping_proto",id:"shopping_proto"}] },
      { id:"F6", t:"Style catalog 18 → 62", sub:"DecorAI name parity, 44 new style-card images", when:"Sep 12–13", docs:[] }
    ],
    journal:[
      {d:"Sep 6", h:"Research — home decorating", w:"What exists, what people complain about", docs:["research"]},
      {d:"Sep 6", h:"Spec page opened", w:"10 rounds and 42 decisions begin", docs:["spec"]},
      {d:"Sep 8", h:"Positioning written", w:"Two days after the spec started — out of order", docs:["positioning"]},
      {d:"Sep 9", h:"The spike proved the mechanism", w:"Inpainting with a mask held. The spec was rewritten around what the spike proved.", docs:["spike"], turn:true},
      {d:"Sep 9", h:"Contract frozen", w:"12 routes as generated code, CI drift check", docs:["contract"]},
      {d:"Sep 9", h:"v1 — the initial build", w:"40 commits in one day: the backend baseline and the iOS core", docs:[]},
      {d:"Sep 10", h:"Visual redesign v2 · Style library 6 → 18", w:"Two features, two review pages", docs:["ui_design_v2","prompt_review"], side:true},
      {d:"Sep 11", h:"The options round", w:"7 review rounds — the longest review of the app", docs:["options_review"], side:true},
      {d:"Sep 11–12", h:"Shop your restyle", w:"Research, then options A/B/C, then a prototype, then built", docs:["search_research","shopping_research","shopping_proto"], side:true},
      {d:"Sep 12", h:"PRD exported · style catalog 18 → 62", w:"19 sections generated from the page", docs:["prd"]},
      {d:"Sep 13", h:"Both branches merged", w:"Last commit on main", docs:[]},
      {d:"Sep 17", h:"Screens snapshot reviewed", w:"The real app, as merged, walked through in 6 comments", docs:["app_snapshot"], side:true}
    ]
  },
  // read-only document copies
  docs:{
    spec:{t:"app_1 — Product & Technical Spec", k:"html-worker", where:"app_1/spec/", rounds:10, dec:42, when:"Sep 6 → 9",
      what:"The PRD, decided on one page across ten rounds. Exported to PRD.md on Sep 12.",
      list:[["u2","U2 mask display","Outline only"],["u3","U3 verify layout","Stacked before and after"],["u4","U4 style picker","Scrollable image cards"],["t1","T1 image model","A hosted image API"],["t2","T2 database","PostgreSQL"],["t3","T3 photo storage","A folder on the server"],["t4","T4 job updates","Ask every 2 seconds"],["t5","T5 auth build vs buy","Sign in with Apple"],["t6","T6 backend language","Python + FastAPI"],["t7","T7 structure detection","Depth model + segmentation model"],["t8","T8 photo retention","Until the user deletes them"],["t9","T9 queue","A table in Postgres"]], more:30},
    options_review:{t:"Room Options Review", k:"html-worker", where:"app_1/options_review/", rounds:7, dec:6, when:"Sep 11",
      what:"What the user should be able to ask for in a restyle. The longest review in the app — seven rounds.",
      list:[["d1","Which options ship","a-only"],["d2","Option set","walls, add furniture, decor, palette, plants"],["d3","Trim behaviour","trim-only"],["d4","Mode","mode b only"],["d5","Extra controls","nothing"],["d7","Confirm-screen questions","purpose, must fit, how full, palette, surfaces"]], more:0,
      note:"This page builds its decisions in JavaScript rather than as plain radio groups, so a generic flattener has to read them out of the script — see D16."},
    prompt_review:{t:"Style library — 18 styles", k:"html-worker", where:"app_1/prompt_review/", rounds:2, dec:5, when:"Sep 10",
      what:"The style list and how each style is described to the image model.",
      list:[["d1","Style coverage","full"],["d2","Card labels","labelled"],["d3","Ordering","top"],["d5","Existing styles","keep"],["d7","Duplicates","drop"]], more:0},
    ui_design_v2:{t:"DesignMyRoom — visual redesign", k:"html-worker", where:"app_1/ui_design_v2/", rounds:2, dec:2, when:"Sep 10",
      what:"The visual direction for all seven screens, reviewed before any of them were rebuilt.", list:[], more:2},
    search_research:{t:"Finding products cheaply — the ways", k:"html-worker", where:"app_1/search_research/", rounds:2, dec:3, when:"Sep 11",
      what:"How to find real buyable products for the items in a render, and what each route costs.", list:[], more:3},
    shopping_research:{t:"Shop the render — options A, B, C", k:"html-worker", where:"app_1/shopping_research/", rounds:0, dec:0, when:"Sep 11",
      what:"Three ways to build shopping. Built, opened, and never reviewed — zero rounds recorded.",
      list:[], more:0, parked:true},
    shopping_proto:{t:"Shop your restyle — prototype", k:"html-worker", where:"app_1/shopping_proto/", rounds:2, dec:4, when:"Sep 12",
      what:"The shopping screen as a clickable prototype, reviewed before it was built for real.", list:[], more:4},
    app_snapshot:{t:"app_1 iOS — real screens, as merged on main", k:"html-worker", where:"app_1/app_snapshot/", rounds:1, dec:0, when:"Sep 17",
      what:"The actual shipped screens, walked through. Six comments, no decisions — a review of what exists rather than a choice about what to build.", list:[], more:0},
    research:{t:"Research — home decorating", k:"markdown", where:"app_1/research/home-decorating.md", when:"Sep 6",
      what:"Existing decor apps, what they cost, and what real users complain about — every quote verbatim with a link.", list:[], more:0},
    teardown:{t:"DecorAI options teardown", k:"markdown", where:"app_1/research/decorai-options-teardown.md", when:"Sep 12",
      what:"A close read of the competitor's option set, done during the options round.", list:[], more:0},
    positioning:{t:"Positioning", k:"markdown", where:"app_1/positioning.md", when:"Sep 8",
      what:"One paragraph: who it is for, the closest existing product, and the wedge — plus the Anchored-to block of verbatim complaints that unlocked the spec.", list:[], more:0},
    prd:{t:"PRD — app_1", k:"markdown", where:"app_1/PRD.md", when:"Sep 12",
      what:"19 sections, generated from the spec page and its recorded decisions. Never hand-written.", list:[], more:0},
    contract:{t:"contract/openapi.json", k:"generated", where:"app_1/contract/", when:"Sep 9",
      what:"12 routes. Generated from schemas.py and the route signatures; never edited by hand. CI fails the build if it drifts.", list:[], more:0},
    handoff:{t:"HANDOFF.md", k:"markdown", where:"app_1/HANDOFF.md", when:"Sep 10",
      what:"The orchestrator's context for a fresh session: who is building what, what is in flight, and the gotchas.", list:[], more:0},
    orch:{t:"ORCH-QUESTIONS.md", k:"markdown", where:"app_1/ORCH-QUESTIONS.md", when:"Sep 12",
      what:"12 numbered questions from the two workers, answered inline by the orchestrator. The only way the frozen contract is allowed to change.", list:[], more:0},
    spike:{t:"spike/", k:"code", where:"app_1/spike/", when:"Sep 9",
      what:"The throwaway script that proved masked inpainting preserves the room's architecture. It worked, and the spec was rewritten around it the same day.", list:[], more:0}
  }
};
